#!/bin/bash
[[ -z "${PS1+x}" ]] && set -euo pipefail

MPICC=${MPICC:-mpicc}
MPICXX=${MPICXX:-mpicxx}

$MPICXX --version

CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_PROFILER_MODE=$KOCHI_PARAM_PROF"
CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_ORI_DEFAULT_MEM_MAPPER=$KOCHI_PARAM_DIST_POLICY"
CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_ORI_BLOCK_SIZE=$KOCHI_PARAM_BLOCK_SIZE"

case $KOCHI_PARAM_CACHE_POLICY in
  serial)            CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_ITO_SCHEDULER=serial" ;;
  nocache)           CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_POLICY=ityr_policy_workfirst -DITYR_IRO_DISABLE_CACHE=1" ;;
  writethrough)      CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_ORI_ENABLE_WRITE_THROUGH=1" ;;
  writeback)         CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} " ;;
  writeback_lazy)    CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_ORI_ENABLE_LAZY_RELEASE=1" ;;
  getput)            CXXFLAGS="${CXXFLAGS:+$CXXFLAGS} -DITYR_POLICY=ityr_policy_workfirst_lazy -DITYR_IRO_GETPUT=1" ;;
  *)                 echo "Unknown cache policy ($KOCHI_PARAM_CACHE_POLICY)"; exit 1 ;;
esac
